# Generated by Django 4.2.6 on 2023-11-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date'),
        ),
    ]
