# Generated by Django 4.2.6 on 2023-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worklist_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='worklist_date'),
        ),
    ]
